# Generated by Django 3.0.7 on 2020-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gracze',
            fields=[
                ('nazwa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('czas_rozpoczecia', models.DateTimeField()),
                ('max_graczy', models.IntegerField()),
            ],
        ),
    ]
