# Generated by Django 3.0.7 on 2020-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turniej_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnieje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('czas_rozpoczecia', models.DateTimeField()),
                ('max_graczy', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Gracze',
        ),
    ]
