# Generated by Django 3.0.7 on 2020-06-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turniej_app', '0003_gracze'),
    ]

    operations = [
        migrations.AddField(
            model_name='gracze',
            name='turniej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turniej_app.Turnieje'),
        ),
    ]
